# Generated by Django 2.1.2 on 2018-10-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_title',
            field=models.CharField(default='sample_title', max_length=50),
            preserve_default=False,
        ),
    ]
