# Generated by Django 2.1.2 on 2018-10-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_note_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='deadline',
            field=models.DateTimeField(default='2020-01-01 00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
